# JWT signing secret. Generated by Terraform on first apply, stored as an
# SSM SecureString. The Lambda fetches it at cold-start (cached for the
# container's lifetime) — no plaintext in env vars, no manual rotation step.
#
# Rotation: untaint + re-apply rotates the secret. All in-flight tokens
# become invalid; reviewers will see a 401 next request and re-verify by
# email. Acceptable for our scale; revisit if active session count climbs.
resource "random_password" "jwt_secret" {
  length  = 64
  special = false
}

resource "aws_ssm_parameter" "jwt_secret" {
  name        = "/${var.environment}/${var.service_name}/jwt-secret"
  description = "HS256 signing key for Epilepsy CDE Explorer API tokens."
  type        = "SecureString"
  value       = random_password.jwt_secret.result

  lifecycle {
    # Letting TF rotate the secret on every change to `random_password` is
    # appropriate; logging it in apply output isn't.
    ignore_changes = [value]
  }
}
